### ISSUE TITLE
Gray unreadable font in light theme

### ISSUE THREAD

**Issue by natarslan** [andrewmcgivery/obsidian-beautitab#12]
Thanks for this fantastic plugin. Its beautiful.

I relaised that the fonts are white and readable when I use dark (minimal) theme but as soon I switch to the light theme the fonts are grayed out and become almost unreadable. I will attach a file.

![Screenshot (219)](https://github.com/andrewmcgivery/obsidian-beautitab/assets/15086016/50ee43da-8c2a-4a09-be7d-74fc28d1ee53)

**Comment by ernest67** [comment]
This happens to me as well

**Comment by andrewmcgivery** [comment]
Ahhhh good catch. Will fix this ASAP. :)

**Comment by andrewmcgivery** [comment]
Should now be fixed in version 1.1.1 (just released). :)

Thanks for reporting!

**Comment by natarslan** [comment]
Thanks for the quick fix!
