### ISSUE TITLE
Incompatible with Plugin Groups

### ISSUE THREAD

**Issue by Kirxii** [andrewmcgivery/obsidian-beautitab#13]
The community plugin's search engine (omnisearch, quick switcher++) being activated by the community plugin Plugin Groups won't work with the search buttons

![image](https://github.com/andrewmcgivery/obsidian-beautitab/assets/131458787/f5dab9d4-c98b-4dc0-bbbb-bdbeac88b7dd)
![image](https://github.com/andrewmcgivery/obsidian-beautitab/assets/131458787/b9368255-1e03-4946-a10d-3d0d04722cee)

I could still use workarounds like enabling it directly in Obsidian, but it would be nice for it to be compatible if that's possible
Love the plugin ❤

**Comment by andrewmcgivery** [comment]
I'll look into this! :)

**Comment by andrewmcgivery** [comment]
Fixed in version 1.6.0 (just released). :)
