### ISSUE TITLE
[FR]: Time of Day (morning/afternoon/evening etc.) Greeting 

### ISSUE THREAD

**Issue by phthallo** [andrewmcgivery/obsidian-beautitab#18]
New Tab extensions tend to have a personalised greeting showing based on the time of day, e.g "Good morning, <name>". I'd love for this option to be added to the plugin, letting users to specify a placeholder variable for that time of day. 

For instance, inputting "Good, {{date}}, Myname" as greeting text would then show "Good morning, Myname" on the new tab page in the morning. Likewise, in the afternoon it'd show "Good afternoon, Myname". Doing this would allow for freedom of customisation, too, if users wanted to make their greeting instead "it's a beautiful {{date}}" or whatever. 
Of course, if you can think about another easier way to implement this, that'd be great too!

Thanks for working on this plugin! It's super cool :)

**Comment by andrewmcgivery** [comment]
This is now supported in version 1.3.0 (just released). :)
