### ISSUE TITLE
Does not seem to size for mobile

### ISSUE THREAD

**Issue by EntropicNinja** [andrewmcgivery/obsidian-beautitab#21]
Hey, just came across your reddit post & installed stright away. Love this idea and where it's heading.

Just to let you know that I've so far only tried it on mobile and it has some formatting issues:

1. The whole thing (time, search, greeting, recent, quote) could be brought up a bit as the quote doesn't quite fit and falls off the screen at the bottom of the page.
2. The recent files span past the edges of the screen and cuts off some text (could this be scrollable? - can make A FR if so)

![Screenshot_20240215-201558](https://github.com/andrewmcgivery/obsidian-beautitab/assets/8225007/ca66d897-bb76-4a49-ae80-7f1bebb22604)

**Comment by andrewmcgivery** [comment]
Interesting. I haven't actually tried it on mobile at all. I didn't realize it as marked as available for mobile 😓 

Will add it to the list to look at fixing this up a bit! Thanks for raising this!

**Comment by andrewmcgivery** [comment]
@EntropicNinja this should be much better now on version 1.2. Please update and let me know if you run into any more mobile issues!

**Comment by EntropicNinja** [comment]
![Screenshot_20240216-082527](https://github.com/andrewmcgivery/obsidian-beautitab/assets/8225007/dce7c0fe-e983-47d7-8e1f-4a24f1c76ec0)

Hey, thanks for looking into this so quickly, your edit has fixed the issue! 👌

**Comment by EntropicNinja** [comment]
Just noticed the new 1.5 release and loving the local background option. Though I've noticed that in using the 24hr clock late at night the sizing is not refactored making the clock not fit the screen. 

![Screenshot_20240305-234226](https://github.com/andrewmcgivery/obsidian-beautitab/assets/8225007/8ab9d489-99bf-47c3-aa69-5ad3b56b38b4)
