### ISSUE TITLE
The adaptation in split-screen view has some issues.

### ISSUE THREAD

**Issue by PupupupuTong** [andrewmcgivery/obsidian-beautitab#23]
As shown in the image.

![image](https://github.com/andrewmcgivery/obsidian-beautitab/assets/69069739/c05a5556-b237-40c8-a1e1-8a8604478b29)

The size on my computer defaults to one-quarter of the screen. I noticed that when I drag it to about one-third of the screen width, the search box can fully appear.

Furthermore, when I open a new tab in the floating window or adjust the page width, at a certain width, the size of the time and search box suddenly changes significantly, rather than smoothly scaling.

**Comment by andrewmcgivery** [comment]
This should not downsize more smoothly and work properly on split screen in latest update (just pushed).

Thanks for reporting. :)
