### ISSUE TITLE
Beautitab disappears when enabling bookmarks on mobile

### ISSUE THREAD

**Issue by EntropicNinja** [andrewmcgivery/obsidian-beautitab#24]
When I enable bookmarks beautitab fails to display on mobile. But I also can not see the default new tab page either!

- I've disabled the dynamic background plugin just in case it was interfering, no change in behaviour. 
- I have tried disabling inline search, no change.
- I have added bookmarks to a folder and selected that folder. No change
- I put the clock back to 12 hr and enabled bookmarks. No change.

I can only make it work when I don't enable bookmarks. Everything else works fine.

**Comment by andrewmcgivery** [comment]
Thank you for the report!

Turns out there is a bug within Obsidian's bookmark plugin that I had to account for. This should be fixed now in version 1.4.1. :)
