### ISSUE TITLE
Background image issues

### ISSUE THREAD

**Issue by Smitty010** [andrewmcgivery/obsidian-beautitab#34]
I have images set to "Mountains".  Here's what I get
![image](https://github.com/andrewmcgivery/obsidian-beautitab/assets/3760075/91fad7f6-bf5b-48b5-b153-a0070d7a50df)
I don't think that's mountains

**Comment by andrewmcgivery** [comment]
lol! Unfortunately, you'd have to take that up with the person who uploaded that to unsplash with that tag.

This plugin pulls random images by a tag but that images are not curated.

**Comment by Smitty010** [comment]
OK.  Not a huge deal
