### ISSUE TITLE
Clock on mobile sizing issue

### ISSUE THREAD

**Issue by EntropicNinja** [andrewmcgivery/obsidian-beautitab#37]
Just noticed the new 1.5 release and loving the local background option. Though I've noticed that in using the 24hr clock late at night the sizing is not refactored making the clock not fit the screen.

![Screenshot_20240305-234226](https://github.com/andrewmcgivery/obsidian-beautitab/assets/8225007/1b2fa422-7999-4ee4-83a0-5681c65e462e)

**Comment by andrewmcgivery** [comment]
Fixed in version 1.6.0 (just released). :)
