### ISSUE TITLE
[FR] Create a new file and choose its folder

### ISSUE THREAD

**Issue by EntropicNinja** [andrewmcgivery/obsidian-beautitab#38]
Wondering about an option to create a new file, say a plus icon, that when clicked will initiate a "choose your folder" palette to popup akin to when you move a file. Allowing you create a file in that folder, & open it ready to be renamed like any other new file.

As a second thought, if this is implemented maybe templater could be integrated/initiated at creation as well. Or a way for other plugins to be tied in.

**Comment by andrewmcgivery** [comment]
As of version 1.6.0 (just released), this is now possible via Commander (add button to Tab Bar) and Quick Add. :)
