### ISSUE TITLE
Cannot use Hotkeys from beautitab

### ISSUE THREAD

**Issue by Dars90** [andrewmcgivery/obsidian-beautitab#44]
Pressing Ctrl or alt when trying to use hotkeys from beautitab appears to be bringing up the search bar. Cannot use hotkey for command palette for instance

**Comment by brimwats** [comment]
Same. Turning off the search bars (inline and left) reeables them

**Comment by brimwats** [comment]
Disegard that! Doesn't fix it even when off.

**Comment by Eflores89** [comment]
loved the plugin but this makes it unusable - turning off for now.

**Comment by LemurTech** [comment]
What they said. Unusable in it's current state.

**Comment by andrewmcgivery** [comment]
Apologies for the late response! Been busy. :)

This should be fixed with version 1.6.1.

Please update and if the issue persists, please open a new issue. :)

Thanks for reporting!
