### ISSUE TITLE
[FR]: Open file in the same tabs

### ISSUE THREAD

**Issue by Lisandra-dev** [andrewmcgivery/obsidian-beautitab#5]
It's very disturbing that file open in a new tabs instead of the same tabs, as the default Obsidian behavior.

It is possible to change this?

I tried to edit the code, but I don't have enough knowledge in React to edit this behavior.
I noticed the cause : it's around the `onOpen()` here: https://github.com/andrewmcgivery/obsidian-beautitab/blob/ed61b5383c2e8507520bd89127e02f30f6059dad/Views/ReactView.tsx#L32-L40

Removing all in the `onOpen()` keep the behavior, so I think the way you implemented the React have a problem with that.

Another way is to switch to the opened file and close the old tabs, but I can't get this behavior to work on my side :(

**Comment by andrewmcgivery** [comment]
Hi @Lisandra-dev!

This was something that I was struggling to figure out that I just found the solution to. The issue was that I was using a `ItemView` instead of a `FileView` so Obsidian (and other plugins) couldn't open files in it.

I'll be pushing a fix to this soon. :)

**Comment by andrewmcgivery** [comment]
Just pushed version 1.0.1. Should be fixed in that version. :)

Thanks for reporting!

**Comment by Lisandra-dev** [comment]
Thank you a lot !!
