### ISSUE TITLE
Recent Files aren't working

### ISSUE THREAD

**Issue by bobbleheadjoe** [andrewmcgivery/obsidian-beautitab#8]
Wonderful plugin! 👏 My issue is that the recent files don't actually show recent files... Seems to be grabbing my oldest Daily Notes instead. Perhaps it's finding things in alphabetical order in my vault? Even when I open other files, quit, and reopen Obsidian from scratch, these never change for me.
![CleanShot 2024-01-27 at 09 04 38@2x](https://github.com/andrewmcgivery/obsidian-beautitab/assets/65831760/0b4c70a4-39b8-43c7-845c-3d77a4eb11c5)

**Comment by andrewmcgivery** [comment]
Hey! Thanks for opening an issue!

So to clarify, "recent files" is currently getting the most recently **modified** markdown files.

Are not not seeing this behavior or are there non-markdown files you'd like to see reflected here? :)

**Comment by andrewmcgivery** [comment]
Closing for now. :)
