### ISSUE TITLE
[FR]: Ability to change time format to 24-hours

### ISSUE THREAD

**Issue by mrjackphil** [andrewmcgivery/obsidian-beautitab#9]
Currently it supports only 12-hours format.

It's not a big deal but inconvenience.

**Comment by andrewmcgivery** [comment]
Thanks for opening this issue! Great idea.

Will add that to the TODO list. :)

**Comment by andrewmcgivery** [comment]
This is now supported in version 1.3.0 (just released). :)

**Comment by mrjackphil** [comment]
Thank you! That's super cool!
